server:
  ssl:
    key-store: C:\\Users\\arnol\\mykeystore.jks
    key-store-password: tacopassword
    key-password: tacopassword
    certificate: C:\\arnol\\mycert.crt
  port: 8443

spring:
  datasource:
    url: jdbc:h2:~/tacodb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    rest:
      base-path: /api

logging:
  file:
    path: /var/logs/TacoCloud.log
  level:
    root: INFO
    tacos: INFO
    org:
      hibernate:
        SQL: INFO
      springframework.security: INFO

taco:
  orders:
    page-size: 10