
#Introduced in chapter 5
#Setting my application to read request from port 2023 :
#To check keystore in cmd : (keytool -list -v -keystore mykeystore.jks)

# key-store: C:\\Users\\arnol\\mykeystore.jks
# certificate: C:\\arnol\\mycert.crt


#key-alias: server
#trust-store: classpath:SSL/truststore.p12
#trust-store-password: tacopassword
#trust-store-type: PKCS12
#client-auth: none

Server:
  port: 9090
  #ssl:
  #  key-store: classpath:SSL/server-keystore.p12
  #  key-store-password: tacopassword
  #  key-store-type: PKCS12





spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacodata
    username: tacocloud
    password: tacopassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    rest:
      base-path: /api
  jmx:
    enabled: true

  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: tacopassword
  application:
    name: Cliff Taco Cloud

logging:
  level:
    root: warn

#logging:
##file:
#   path: /var/logs/TacoCloud.log
# level:
#   root: INFO
#   tacos: INFO
#   org:
#     hibernate:
#        SQL: WARN
#      springframework.security: INFO

taco:
  orders:
    page-size: 10

management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
       include: '*'
      # exclude: '*'
      # base-path: /management

# Touches on actuactor/info
info:
  contact:
    email: clifftacocloud@gmail.com
    phone: 822-625-6831


